[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/ubeimar_yepes/proyecto/infra/terraform/zt-voting.pem
ansible_ssh_common_args=-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
admin_cidr=186.99.214.144/32
repo_url=https://github.com/UbeimarY/TrabajoFinalSistema.git
repo_ref=main

[vm_api]
vm-api ansible_host=32.198.116.206 private_ip=10.10.0.81

[vm_auth]
vm-auth ansible_host=10.10.1.73 private_ip=10.10.1.73 ansible_ssh_executable=/home/ubeimar_yepes/proxy-ssh.sh

[vm_brokers]
vm-brokers ansible_host=10.10.1.162 private_ip=10.10.1.162 ansible_ssh_executable=/home/ubeimar_yepes/proxy-ssh.sh

[vm_init]
vm-init ansible_host=10.10.1.123 private_ip=10.10.1.123 ansible_ssh_executable=/home/ubeimar_yepes/proxy-ssh.sh

[vm_core]
vm-core ansible_host=10.10.1.33 private_ip=10.10.1.33 ansible_ssh_executable=/home/ubeimar_yepes/proxy-ssh.sh

[vm_app]
vm-app ansible_host=10.10.1.199 private_ip=10.10.1.199 ansible_ssh_executable=/home/ubeimar_yepes/proxy-ssh.sh
